### ISSUE TITLE
Rageweb is down!! Where are you?

### ISSUE THREAD

**Issue by DanilaFe** [siphontv/skellyweb#7]

**Comment by eadle** [comment]
:^)

**Comment by Alibih** [comment]
WHAT DID YOU DO TO UPCOMING GOTY?

**Comment by eadle** [comment]
I started another side-project. So it looks like another repository becomes abandonware.

**Comment by DanilaFe** [comment]
At least keep it up so we can like talk there

**Comment by eadle** [comment]
167.114.185.203/rageweb

It's going to be completely barren since it's running on a subdirectory. I'm wrapping the chat around the livestreaming prototype though. I'll give you a shout when that happens.

**Comment by eadle** [comment]
Down for the count.
